# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.IntegerField(blank=True, db_column='ProjectID', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'SSim_Project',
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.IntegerField(db_column='ScenarioID')),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('author', models.TextField(blank=True, db_column='Author', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('is_read_only', models.BooleanField(db_column='IsReadOnly')),
                ('runstatus', models.IntegerField(blank=True, db_column='RunStatus', null=True)),
                ('runlog', models.TextField(blank=True, db_column='RunLog', null=True)),
                ('last_modified', models.DateTimeField(blank=True, db_column='DateLastModified', null=True)),
                ('project', models.ForeignKey(db_column='ProjectID', on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'SSim_Scenario',
            },
        ),
        migrations.CreateModel(
            name='SyncroSim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('db', models.FileField(upload_to=b'')),
                ('upload', models.FileField(blank=True, null=True, upload_to=b'')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['db'],
                'verbose_name_plural': 'syncro sim',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='ssim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SyncroSim'),
        ),
    ]
