# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160715_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterstore',
            name='iteration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='rasters',
            field=models.ManyToManyField(to='app.RasterStore'),
        ),
    ]
