# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-08 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160726_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='rasterstore',
            name='scenarioval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
