# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-17 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='label',
            field=models.TextField(blank=True, db_column='label', null=True),
        ),
    ]
